### ISSUE TITLE
Browsersync doesn't work on the first jekyll-build

### ISSUE THREAD

**Issue by AchillesKal** [AchillesKal/Gulpkyll#3]
Browsersync doesn't work on the first jekyll-build.

**Comment by dimitrisdervas** [comment]
δες εδώ https://github.com/shakyShane/jekyll-gulp-sass-browser-sync/blob/master/gulpfile.js

**Comment by AchillesKal** [comment]
Ναι από εκεί τα έβλεπα ... απλά μόλις τώρα κατάλαβα ότι το ['task']
σημαίνει dependent task  :)

2015-12-23 22:14 GMT+02:00 dimitrisdervas <notifications@github.com>:

> δες εδώ
> https://github.com/shakyShane/jekyll-gulp-sass-browser-sync/blob/master/gulpfile.js
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AchillesKal/Gulpkyll/issues/3#issuecomment-166982962>.
>



-- 
Achilles Kaloeridis
